### PR TITLE
Set current site in sites reducer

### PR DESCRIPTION
**Pull request by el-mapache**

### CODE REVIEW

**Comment by jseppi** [comment]
screen shot 2018-02-07 at 12 14 29 pm
screen shot 2018-02-07 at 12 20 24 pm

**Comment by el-mapache** [comment]
The prop warning has been present in the codebase at least since I came back to working on this project. I've got another PR ready to go to fix it.

**Comment by el-mapache** [comment]
I'll add code and a test for updating the current site on delete as well. Theoretically though, we should just get dumped back into the sites list and the current site shouldn't even matter...

**Comment by jseppi** [comment]
Oh, yikes. Thanks!


On Feb 7, 2018, at 1:11 PM, Adam B <notifications@github.com> wrote:

The prop warning has been present in the codebase at least since I came
back to working on this project. I've got another PR ready to go to fix it.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/18F/federalist/pull/1594#issuecomment-363877111>, or mute
the thread

**Comment by el-mapache** [comment]
@seppi should be resolved!

**Pull request merged**
