### PR TITLE
Remediate ws vulnerability by disabling websockets entirely

### PR DESCRIPTION
**Pull request by jmhooper**
This commit entirely disables the `sockets` and `pubsub` Sails hooks so the DOS vulnerability in the `ws` modules is never exposed. We don't actually use websockets at this point so there is no real point in keeping this code around.

This commit also cleans up some old code paths that leaned on web sockets.

ref: https://gist.github.com/mikermcneil/8911041
ref: #609

### CODE REVIEW

**Comment by wslack** [comment]
@jmhooper Travis is unhappy? 

```Failed at the federalist@0.0.0 test:server script 'NODE_ENV=test mocha --timeout 5000 test/api/bootstrap.test.js test/api/unit/**/*.test.js test/api/requests/**/*.test.js'.```

**Comment by jmhooper** [comment]
I believe that is unrelated to this change. I opened #627 to deal with it.

**Comment by brandocalrissian** [comment]
This PR makes sense. Might as well wait until #627 is fixed and this build goes green before merging. Would feel completely confident once we no longer have to say we "believe" we know the travis failure is unrelated to the change.

**Comment by jmhooper** [comment]
This is rebased with the commit from #627 merged. Will wait on Travis then merge.

**Comment by wslack** [comment]
@jmhooper needs to rebase!

**Comment by brandocalrissian** [comment]
staging moved after the last rebase to cause this to get back out of sync

**Comment by brandocalrissian** [comment]
good to go.

**Pull request merged**
