### PR TITLE
Add gatsby uswds template to template options in app.

### PR DESCRIPTION
**Pull request by davemcorwin**
Will need to test in staging to confirm it works!

### CODE REVIEW

**Comment by eddietejeda** [comment]
While you are at it... mind adding the new Jekyll one as well?

**Comment by davemcorwin** [comment]
@eddietejeda not at all, which repo?

**Comment by eddietejeda** [comment]
https://github.com/18F/federalist-uswds-jekyll

**Comment by davemcorwin** [comment]
@eddietejeda added new uswds jekyll template!

**Pull request merged**
