### PR TITLE
[FED-356]: Normalizes viewLink href across buttons

### PR DESCRIPTION
**Pull request by el-mapache**
Addresses issue https://github.com/18F/federalist/issues/356

* Adds viewLink property to toJSON method of `Site` model
* Uses this property to provide an external site url across buttons

### CODE REVIEW

**Comment by jeremiak** [comment]
Nice, its good to have this variable in one place. Those URLs aren't working for some reason though, and  I think we actually want the production build URLs (in the case where a custom URL isn't set) to be something more like `https://s3.amazonaws.com/${awsBucketName}/site/${owner}/${repository}/index.html`

So far though the sites I have checked out look broken at this URL because assets generally aren't delivered properly. It makes me think that we want to supply a baseurl for the Jekyll site if there isn't a custom url when the build is on the default branch.

**Comment by el-mapache** [comment]
I was under the impression that the siteRoot was always set by the app?

When you say it doesn't work, what do you mean? Locally, for me, I have never been able to click 'view site' as the URL always points to my localhost. What I mean is, this PR doesn't actually address not being able to view the site on the internet from a local machine; I was under the impression that never worked.

**Comment by el-mapache** [comment]
I just hardcoded the default path to be the one mentioned in the issue.

**Comment by jeremiak** [comment]
Cool, we might want to make this a config variable or something later but for now this is great!

**Pull request merged**
