### PR TITLE
add "contact us" link

### PR DESCRIPTION
**Pull request by wslack**
Per @line47

### CODE REVIEW

**Comment by jseppi** [comment]
oooooh I think we could make that `90` a "live" value like our number of builds in the past week.

**Comment by wslack** [comment]
Alas, no - the number of live sites is inherited from compliance, not from any old repos that were added.

**Comment by wslack** [comment]
however, we can update that every two weeks

**Comment by line47** [comment]
That would be rad if we could use a `live` number

**Pull request merged**
