### PR TITLE
Tweaks to github and view-site icons

### PR DESCRIPTION
**Pull request by ericronne**
- Shrunk github and “view site” icons, since they overpowered when
shown multiple times on a page
- Slightly adjusted positioning
- Moved “(you)” into the collaborator link

### CODE REVIEW

**Comment by ericronne** [comment]
image

image
image

**Comment by jseppi** [comment]
Hey, what happened here? This PR was made against `master` instead of against `staging`. Was that intentional? That means this code is not in `staging`.

**Comment by ericronne** [comment]
Not intentional 🙇

**Comment by wslack** [comment]
Oh darn it. I caught this once but not this time. Eric, can you please pr these changes into staging as well?

**Comment by ericronne** [comment]
pr #1670 should remedy 🤞

**Pull request merged**
