### PR TITLE
updating cells per row

### PR DESCRIPTION
**Pull request by wslack**
ama @jseppi this is what I wanted to change

### CODE REVIEW

**Comment by jseppi** [comment]
What's your favorite type of pie?

**Comment by jseppi** [comment]
Looks good to me:

screen shot 2017-10-26 at 12 39 52 pm

**Comment by jseppi** [comment]
Well, I mean, it looks better than the 3-per-row version with the fourth one hanging on its own.

**Comment by wslack** [comment]
Spinach Pie!

**Pull request merged**
