### PR TITLE
Updates bucket refs, adds preview link button, cleans up readme

### PR DESCRIPTION
**Pull request by el-mapache**
- Removes out of date info from the README
- Adds explicit instruction to developer to export the s3 bucket name as an env variable
- Fixes s3 bucket refs, adds defaults for cloud.gov on GovCloud
- Adds preview link button

### CODE REVIEW

**Comment by wslack** [comment]
The README edits look good; I can't speak to the JS.

**Comment by brandocalrissian** [comment]
Can we fix the travis and circleci failures? They look to be related to the changes.

**Comment by el-mapache** [comment]
Can we disable the circle integrations? I don't think we need two CI services running on this application.

**Comment by brandocalrissian** [comment]
No major comments. Looks good. Merging.

**Pull request merged**
