### PR TITLE
Setup scanjs rules in eslint

### PR DESCRIPTION
**Pull request by jseppi**
As required by the [Before You Ship guide](https://before-you-ship.18f.gov/security/static-analysis/#javascript).

ref #1073

- Change .eslintrc files into JavaScript .eslintrc.js files
- Only include scanjs and no-unsanitized plugins and rules when scanjs-rules is able to be `require`'d. This prevents eslint in Code Climate from attempting to run those plugins/rules, because they are not available there and will error out.

- [x] Should wait to merge until #1070 is merged so we can make sure it works with CodeClimate

### CODE REVIEW

**Comment by jseppi** [comment]
screen shot 2017-07-19 at 10 29 00 am

😬

**Comment by jseppi** [comment]
Trying to look into this, but Code Climate's website gives me a `504 Gateway Timeout` when I try to  access the [details link](https://codeclimate.com/github/18F/federalist/pull/1075).

**Comment by jseppi** [comment]
Code Climate doesn't support the scanjs plugin, so I am guessing that's why so many errors are generated. And will all the errors their server is bombing out trying to load the details page.

Here's the list of supported plugins: https://docs.codeclimate.com/v1.0/docs/eslint#section-eslint-3

I'm not sure what to do now. Seems we're at an impasse with what Before You Ship recommends versus what is possible.

**Comment by jseppi** [comment]
Going to try this approach:

- Make new `.eslintrc.codeclimate.json` file that does not have scanjs
- Point `.codeclimate.yml` at that file
- Change our root `.eslintrc` to extend `.eslintrc.codeclimate.json` and keey the scanjs rules in that file

This might cause some weirdness due to our descendent `test/.eslintrc` but I'll see what happens.

**Comment by jseppi** [comment]
Latest commit got rid of the 21000 errors, but now having problems with `mocha` stuff not being defined. I could add `env: mocha` to the new `.eslintrc.codeclimate.json` file, but then we'll have multiple configs that could end up out-of-sync :\

**Comment by jseppi** [comment]
What do you think of this approach, @jmhooper? It seems a bit silly to me to have to maintain separate configs, but I'm not really sure what else to do.

**Comment by jmhooper** [comment]
I agree. I'd wait to hear back from infrastructure. I'd think it defeats the purpose to have ScanJS configured, but not use it all. I'm also not a fan of the duplication between the configs.

**Comment by jseppi** [comment]
It's still used by our Travis config and local editor plugins

**Comment by jseppi** [comment]
@jmhooper: Let me know if you think this is 👍 and then I'll clean up the commit history and implement a similar thing over in federalist-builder.

**Comment by jseppi** [comment]
Neither did I. I learned it from Code Climate actually, which was reporting that our extension-less `.eslintrc` files were deprecated and to please use an extension.

**Pull request merged**
