### PR TITLE
update link color to allow for required contrast

### PR DESCRIPTION
**Pull request by wslack**

### CODE REVIEW

**Comment by maya** [comment]
This works, but if you want to use a darker tone of the existing color, you could use: #007d98. If you have a visual designer on hand to check that would be nice, otherwise whichever you prefer.

**Comment by wslack** [comment]
I'll check in staging after merge, I thank. Thanks!

**Comment by jseppi** [comment]
With color @wslack used:
slack color

With color @maya suggested:
maya color

**Comment by jseppi** [comment]
I prefer the first option

**Comment by wslack** [comment]
@jseppi do you think its "too blue" compared to the more gray colors on the page?

**Comment by jseppi** [comment]
Looks fine to these untrained eyes

**Pull request merged**
