### PR TITLE
Add organization whitelist instructions to readme

### PR DESCRIPTION
**Pull request by timwis**
Had to dig into the code a bit to figure out why I couldn't login locally. Thought this might help.

### CODE REVIEW

**Comment by timwis** [comment]
By the way, this is an awesome project. I was just thinking over the weekend about what a CMS should look like if it were designed in 2016...

**Comment by adborden** [comment]
Awesome, thanks for the extra docs. Instead of changing `config/passport.js`, you should edit `config/local.js`. So instead of just a README change, can you also add an `passport.github.organizations` placeholder to the `config/local.sample.js`?

**Comment by timwis** [comment]
Hey guys, sorry for the delay. I've updated the pull request as @adborden suggested. Hope this is what you're after.

**Comment by adborden** [comment]
Awesome, this is great!

**Comment by wslack** [comment]
@timwis I wanted to make sure I said "thank you" for these - I've flagged them in our PM tool but can't promise how soon we'll get to them (I'm trying to get things organized for when we have more devs).

**Comment by timwis** [comment]
No worries!

**Comment by jeremiak** [comment]
Echoing the gratitude above!

@el-mapache this might be a good place (once its merged or cherry picked onto a branch) to add the tips you learned trying to get it up and running locally.

**Comment by skonzem** [comment]
👍 

These additional instructions and a `bundle install` were what I needed to get up and running locally. Plus adding an organization, of course.

**Comment by el-mapache** [comment]
@timwis Would you mind rebasing this PR on top of master? We've fixed the integration test issues for contributors and the PR should successfully build on out CI. Thanks!

**Comment by wslack** [comment]
@timwis LMK if you need a new PR opened for this one as well!

**Comment by timwis** [comment]
Sure @wslack if you wouldn't mind

**Comment by wslack** [comment]
Done, see #434. Closing this one.

**Pull request closed without merging**
