### PR TITLE
allow Slash names in branch names

### PR DESCRIPTION
**Pull request by amirbey**

### CODE REVIEW

**Comment by amirbey** [comment]
tested https://federalist-proxy-staging.app.cloud.gov/preview/amirbey/test7/s/ash/#ii-morem-ipsum

**Comment by jmhooper** [comment]
If the branch name has a slash, are confident that `federalist-preivew.app.cloud.gov/preview/18f/my/branch/name/file` will point to the right place?

**Comment by amirbey** [comment]
@jmhooper  - i tested this .. please see the link above. the site rendered properly for the preview page. are there additional scenarios you forsee as concerning?

**Comment by jmhooper** [comment]
Interesting, yeah seems to work

**Pull request merged**
