### PR TITLE
Icon work

### PR DESCRIPTION
**Pull request by ericronne**
Icon mods

### Screenshot from homepage

screen shot 2018-01-30 at 10 59 27 am

### Screenshots from application

screen shot 2018-01-30 at 10 59 38 am

screen shot 2018-01-30 at 10 59 49 am

screen shot 2018-01-30 at 11 00 07 am

### CODE REVIEW

**Comment by wslack** [comment]
SO EXCITED!

**Comment by ericronne** [comment]
image

**Comment by line47** [comment]
CC @wslack

**Comment by ericronne** [comment]
Closes #1540

**Pull request merged**
