### PR TITLE
Update node and npm versions for security

### PR DESCRIPTION
**Pull request by cwonrails**
Node has updated both v4 LTS and npm v2 to address security concerns (relevant blog post [here](https://nodejs.org/en/blog/vulnerability/openssl-may-2016/)). This PR updates the hard-coded node and npm versions in the travis config, Dockerfile, and package.json to match the most recent secure versions.

Edit: Looking at the Travis logs, the failure occurred at the same point as https://github.com/18F/federalist/pull/327 (Selenium). As soon as it gets fixed up I'll gladly rebase 😄 

Visual reference: 
screen shot 2016-05-21 at 10 24 31 am

### CODE REVIEW

**Comment by wslack** [comment]
Thank you @cwonrails! I can't promise we can get to this immediately but I've flagged it in our PM tool.

**Comment by el-mapache** [comment]
@cwonrails We've disabled integration tests for contributors; you should be able to rebase this branch on top of master and resubmit the PR without getting a failure. Thanks!

**Comment by cwonrails** [comment]
Thanks @el-mapache! I accidentally messed up the rebase for this PR and can't delete it on my end so I made a new one instead: https://github.com/18F/federalist/pull/380

**Comment by wslack** [comment]
Closing per @cwonrails

**Pull request closed without merging**
