### PR TITLE
test change up update add site form

### PR DESCRIPTION
**Pull request by wslack**
I might have done this wrong.

### CODE REVIEW

**Comment by wslack** [comment]
Darn it. Do I want "input?"(based on https://github.com/18F/federalist/blob/e96b83ca9b8436ef5c16b7ae98b31a93b51f4641/test/frontend/components/Fields/InputWithErrorField.test.jsx#L7-L17)

**Comment by wslack** [comment]
@amirbey should we do this in place of https://github.com/18F/federalist/pull/1900 ?

**Comment by amirbey** [comment]
we can move forward with both PRs (as is) because together they complete what you were initially attempting to do when raising this PR.
#1897 - updates the label
#1900 - sets a default value for the default branch check field

**Comment by wslack** [comment]
I retriggered the build in code climate and no result..... https://codeclimate.com/github/18F/federalist/compare/wslack-patch-1#issues

**Pull request merged**
