### PR TITLE
update note about Sauce Labs

### PR DESCRIPTION
**Pull request by wslack**
cc @jeremiak to check me

### CODE REVIEW

**Comment by el-mapache** [comment]
@wslack @jeremiak  Is this still something we should go ahead and merge?

**Comment by jeremiak** [comment]
I don't think we should. This guidance now seems out of date since we're not requiring integration tests on pull requests and it might be confusing to suggest otherwise

**Comment by wslack** [comment]
@jeremiak what should we say? The current guidance is still confusing for outside contributors.

**Comment by wslack** [comment]
Update: @jeremiak is going to rebase and merge this!

**Pull request merged**
