### PR TITLE
Update navigation wording

### PR DESCRIPTION
**Pull request by davidewarren**
"Visit site" changed to "View site" on right side of https://federalist.18f.gov/sites
"Published files" changed to "Uploaded Files" in left nav

### CODE REVIEW

**Comment by wslack** [comment]
Please drop a note in the main channel if the fix isn't working!

**Comment by davidewarren** [comment]
@line47 thanks! I've updated the PR

**Comment by line47** [comment]
This looks good though I did see that on the build page there is a `View website` in the page header that should be updated to `View site`, other than that looks good! 

screen shot 2018-01-31 at 12 00 30 pm

**Comment by davidewarren** [comment]
@wslack yep, this was me not 100% accurately reading the content rules guide - https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit# 

Specifically, Since Website is used in the introduction top left header after first login - then according to the rules the button in the header to the right should be "Add site". Now the PR is updated to reflect this. 

I've got all the changes in now @line47 !

**Comment by line47** [comment]
Looks good to me, @jseppi ?

**Pull request merged**
