### PR TITLE
Update buildpack

### PR DESCRIPTION
**Pull request by jmhooper**
We updated to node 6.9.0 and npm 3.10.8 in #624. Our manifest was hardcoded to use the nodejs buildpack v1.5.4 which does not support those versions of node / npm. This commit updates the manifest to use buildpack v1.5.23 which does support node 6.9.0 and npm 3.10.8.

### CODE REVIEW

**Comment by wslack** [comment]
@jmhooper are we expecting this to fail in Travis (and so should we just immediately merge?)

**Comment by jmhooper** [comment]
Yes, this will auto fail b/c of the webhook API spec. It also will not deploy if the spec fails so the only way to get it to deploy from Travis would be to bypass that spec.

**Comment by jmhooper** [comment]
Okay, this is working on staging now and should be ready to go. Now the changes include:

- Update buildpack
- Update travis config to use node v6
- Delete the staging environment config (we use the production config on staging; see the commit message for details)
- Restructure the production config to be a bit more readable
- Upgrade some node modules so everybody gets along

**Comment by brandocalrissian** [comment]
if the tires have been kicked with these changes on staging, then we should be good to go once the rebase/conflict resolution is complete.

**Comment by brandocalrissian** [comment]
meaning it's good for merging once we make sure the conflicts are nothing to worry about.

**Comment by jmhooper** [comment]
Rebased and waiting.

**Comment by brandocalrissian** [comment]
we're green. merging.

**Pull request merged**
