### PR TITLE
Set default storage to local disk

### PR DESCRIPTION
**Pull request by timwis**
Per [README.md](https://github.com/18F/federalist#using-postgres) documentation:
> By default, the application should use local disk storage in place of a database.

A fresh install  and `npm start` throws errors about the postgres `federalist` database not existing because of this line.

### CODE REVIEW

**Comment by timwis** [comment]
FYI, looks like tests failed because they "couldn't connect to selenium server." Assuming that's not an issue on my end.

**Comment by adborden** [comment]
Hey, thanks for the fix. Sorry about the selenium issue, looks like we overlooked how we can properly integrate Sauce Labs, so we'll have to integrate your changes manually for now. Hang tight!

**Comment by el-mapache** [comment]
@timwis Would you mind rebasing this on top of master? CI issues should be fixed and we'd like to merge this. Thanks!

**Comment by timwis** [comment]
@el-mapache I'm sorry but this is one of those times when git just does something weird. I did the rebase, but it's just not updating this repo. Somehow it thinks it's a fork of brentgardner/federalist... unless you can help me figure out what's going on, I'd say just go ahead and apply the changes manually or cherrypick, no worries about the commit logs.

**Comment by wslack** [comment]
@timwis that happens sometimes; sorry! I went ahead and made a new PR for us to use: https://github.com/18F/federalist/pull/432

**Pull request closed without merging**
