### PR TITLE
Transition to Bootstrap in preparation for initial launch

### LINKED ISSUE #132: Implement Bootstrap as a CSS framework
At this stage in our applications lifecycle, we have outgrown what the Materialize framework affords us and we want our application to look professional as we have two client launches in the month of September.

For now, let's just implement Bootstrap and make small customizations where necessary.

To replace #113

### PR DESCRIPTION
**Pull request by jeremiak**
This PR should change the required CSS framework from Materialize.CSS to Bootstrap, including the `npm` dependencies and scripts to ensure that files are in the correct places.

There should be no change in site functionality, though #127 has been merged in so the organization is quite different.

Here are two sample screenshots:

screen shot 2015-08-25 at 10 05 08 am
screen shot 2015-08-25 at 10 06 13 am

To close #132

### CODE REVIEW

**Comment by dhcole** [comment]
@jeremiak looks great. Amazing how quickly you were able to turn this around. 

Just a few small issues, most likely due to a few events that may not be firing. 

1. Clicking "use this template" on the new site page doesn't seem to do anything
2. After adding a new site (repo-based) I see something that looks like a trailing comment tag:
  screen shot 2015-08-25 at 4 33 09 pm
3. Clicking "delete" doesn't seem to work"

**Comment by jeremiak** [comment]
Thanks @dhcole - changes have been pushed

**Comment by anweiss** [comment]
+1...this looks fantastic! That turnaround time was quite impressive lol

**Comment by dhcole** [comment]
:boot:

**Pull request merged**
