### PR TITLE
Merge to master for re-deploy 1/8/18

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by jseppi** [comment]
Due to the revert commit made to `master` this morning we'll have to do some git work to get the `master` and `staging` back in sync.

**Comment by jseppi** [comment]
Filed https://github.com/18F/federalist/pull/1469

**Comment by wslack** [comment]
The web editor doesn't want to accept my resolve commit

**Comment by wslack** [comment]
got it to accept by unprotecting the staging branch

**Comment by wslack** [comment]
and I've now put protections back into place

**Comment by jseppi** [comment]
Sweet, thanks! Still needs a ✅ from a reviewer before merge.

**Comment by jseppi** [comment]
I think we actually need to revert the revert commit still

**Pull request closed without merging**
