### PR TITLE
add report template

### PR DESCRIPTION
**Pull request by wslack**

### CODE REVIEW

**Comment by jseppi** [comment]
Looks like this:

screen shot 2017-10-26 at 11 57 13 am

**Comment by wslack** [comment]
We really need to make sure that the boxes behaving more intelligently

**Comment by jseppi** [comment]
How would you like them to look?

**Comment by wslack** [comment]
I thought we had it set up to automatically grid them if there were 4. It's also wonly looking because they are different sizes. Not a huge deal though.

**Pull request merged**
