### PR TITLE
Deploy to fix bug with capitalized GitHub usernames

### PR DESCRIPTION
**Pull request by jmhooper**

### CODE REVIEW

**Comment by wslack** [comment]
I'm not 💯  comfortable deploying the webpack changes unless y'all feel like you've had time to find bugs. How comfortable do you feel?

**Comment by jseppi** [comment]
@wslack: I would feel better including the webpack changes in the regular sprint review before deploying them.

**Comment by wslack** [comment]
@jseppi how do you suggest deploying a subset of changes as bugfixes, if you want to wait until next Friday?

**Comment by jseppi** [comment]
I think we could we `git cherry-pick` the bugfix changes (https://github.com/18F/federalist/pull/975/commits/e1778636eb7b374ef9a5cf73d711233ef8241db8 and https://github.com/18F/federalist/pull/975/commits/74a2df37eecf32ef3c4c3f1c493804caa70258c8) into a new branch and open a PR against `master` with that branch.

**Comment by wslack** [comment]
Go for it!

**Comment by jseppi** [comment]
See #979!

**Comment by jseppi** [comment]
Closing this now since #979 has been merged to `master`

**Pull request closed without merging**
