### PR TITLE
User api request specs

### PR DESCRIPTION
**Pull request by jmhooper**
This commit adds request specs for the user API which provide examples for the following actions:

- find
- findOne
- addSite

### CODE REVIEW

**Comment by brandocalrissian** [comment]
Prob needs to base this PR merge off of staging or another branch, not master.

**Comment by brandocalrissian** [comment]
I'm having trouble running the tests. I've nuked my local node_modules and started everything fresh.

> federalist@0.0.0 test:server /Users/brandonkirby/18f/federalist
> NODE_ENV=test mocha --timeout 5000 test/api/bootstrap.test.js test/api/unit/**/*.test.js test/api/requests/**/*.test.js

module.js:340
    throw err;
    ^

Error: Cannot find module 'supertest'

**Comment by jmhooper** [comment]
I push a commit that adds `supertest` to the `package.json`.

This is weird because it should be installed alongside `supertest-as-promised` if your version of npm supports peer dependencies (> 1.2.10 I believe).

**Comment by brandocalrissian** [comment]
Adding the dependency in package certainly helped resolve the library.

There are oodles of missing semicolons, but that's consistent with the test code for the server.

Merging.

**Pull request merged**
