### PR TITLE
Add Org whitelist instructions and sample code

### PR DESCRIPTION
**Pull request by wslack**
Helps user deploy Federalist locally

### CODE REVIEW

**Comment by wslack** [comment]
This replaces https://github.com/18F/federalist/pull/328 because Git is sometimes troublesome.

**Comment by wslack** [comment]
@el-mapache do you have other tips for running locally to add? What about the `bundle install` referenced in this comment: https://github.com/18F/federalist/pull/328#issuecomment-225377134

**Comment by jeremiak** [comment]
Sorry for the round-a-bout, but closing this in favor of 437 which preserves the outside contribution.

**Comment by wslack** [comment]
A-OK

**Pull request closed without merging**
