### PR TITLE
Add more robust UserAction support on front-end

### PR DESCRIPTION
**Pull request by el-mapache**
* Adds reducer, action creators and tests

Screenshot of the new-ish table:

screen shot 2018-01-10 at 11 49 08 am

### CODE REVIEW

**Comment by jseppi** [comment]
screenshot of prop validation error:

screen shot 2018-01-10 at 11 12 23 am

**Comment by el-mapache** [comment]
This error is actually already present in our current app, and I'm not really sure how to fix it without defining a default null object schema for the user action on the front end :/

**Comment by el-mapache** [comment]
It's also not marked as required, as far as I can tell

**Comment by jseppi** [comment]
You're right. This is super weird. Perhaps some issue between `connect` and React?

Found this, which is kind of similar: https://github.com/reactjs/react-redux/issues/6

**Comment by el-mapache** [comment]
I see a lot of issues where libraries are throwing this error but haven't figured out the root cause yet

**Comment by el-mapache** [comment]
this feels like a super goofy workaround but I guess it'll have to do

**Comment by jseppi** [comment]
Well, let's work on it later, because like you noted, I don't see anything wrong in the propTypes declarations for the components here.

**Comment by jseppi** [comment]
Filed https://github.com/18F/federalist/issues/1482

**Pull request merged**
