### PR TITLE
Merge `master` into `staging` to sync icon changes

### PR DESCRIPTION
**Pull request by jseppi**
This should get `staging` back in-line with the PR #1655 that was accidentally pulled directly into `master`

### CODE REVIEW

**Comment by wslack** [comment]
@jseppi I'll leave it to you to do the "update branch" action but I think that might not be a good idea - that will merge staging into master if memory serves.

**Comment by jseppi** [comment]
No, we should **not** `Update branch` because that will cause a production deploy.

**Comment by wslack** [comment]
yup. let's discuss at standup?

**Comment by wslack** [comment]
Everyone else: do *not* click "update branch"

**Comment by jseppi** [comment]
I can admin-merge this into `staging`.

**Comment by wslack** [comment]
👍

**Pull request merged**
