### PR TITLE
set default branch to master when adding a site

### PR DESCRIPTION
**Pull request by amirbey**

### CODE REVIEW

**Comment by wslack** [comment]
@amirbey I don't know why but https://github.com/18F/federalist/commit/ceca31365f7fac2ca347f289242e3a8e31d500b1#diff-16da512ef30dfa120677e78e36133f97 isn't showing up in the PR. Maybe it needs to be rebased?

**Comment by amirbey** [comment]
yes... it shows up as a merge conflict

**Comment by wslack** [comment]
@amirbey are you sure that code should be cut out?

**Comment by wslack** [comment]
https://github.com/18F/federalist/commit/71ab5f10eacbd95c5562524ea267a0930f3ffa58 seems like a pretty large commit....

**Comment by wslack** [comment]
Did we just accidentally undo https://github.com/18F/federalist/pull/1902/files ?

**Pull request merged**
