### PR TITLE
ok, lets add materialcss!

### LINKED ISSUE #26: Front end should look good on any device
The result of #25 is pretty ugly and doesn't work that well for mobile viewports. The app should look professional and render well on phones and desktop machines

### PR DESCRIPTION
**Pull request by jeremiak**
This is our experiment with the [materialcss](http://materializecss.com) design framework. The sites listing page looks something like this 
screen shot 2015-06-10 at 11 19 58 pm

As a fortunate side effect, it will also close #26.

### CODE REVIEW

**Comment by jeremiak** [comment]
hey @dhcole looks like there's a gonna be some merge conflicts. Would you prefer that I merge from master into this branch and add that to the PR so it merges cleanly?

**Comment by dhcole** [comment]
@jeremiak nice. Looks great. Would love to hear your thoughts on this as you get more familiar with the it.

Yea, please resolve the conflict and merge in master.

**Comment by jeremiak** [comment]
Cool, done.

So far the framework is OK. It looks very pretty but the types of elements aren't as varied (read: comprehensive) as Bootstraps and the documentation leaves a bit to be desired. Also, IDK if you noticed but I'm actually getting the [css](https://github.com/18F/federalist/blob/materialcss/assets/index.html#L4) and [js](https://github.com/18F/federalist/blob/materialcss/assets/index.html#L21) for the framework from CDNs because the `npm install` is.... weird and frankly kind of worthless.

**Comment by dhcole** [comment]
OK enough to keep running with it or would you prefer to try something else? Your call. 

Also, we should figure out how to avoid the CDN links -- we generally don't include resources from any third-party domains in our projects (but fine for now).

**Comment by jeremiak** [comment]
Let's just keep going with it for now. It looks pretty and works well enough (we're not doing things that are too complex).

I agree re: pulling out the CDN links. Just for background:
the materialize npm doesn't have a main or any JS for that matter so it just pulls down compiled JS and CSS to `./node-modules/materialize-css/bin/` - we could easily have a small NPM task to move those over to something like `assets/vendor`. How about we merge and use #43?

**Comment by dhcole** [comment]
:+1: 

I'll look into #43. Have an idea there.

**Comment by dhcole** [comment]
@jeremiak Just sharing some thoughts here... Materialize is an implementation of Google's Material, which is just a style guide (as opposed to an official thing from Google). To better understand the how and why for Materialize, I've been reading through the actual Material style-guide: http://www.google.com/design/spec/material-design/introduction.html

I think there's a lot of really interesting research there that we use to inform how we implement Materialize while making the branding our own. 

(I realize there is nothing ground-breaking in this comment :) Just posting for discussion / posterity.)

**Comment by dhcole** [comment]
@bradnunnally also would love your thoughts on the above. Not sure if you're already familiar with Material.

**Pull request merged**
