### PR TITLE
Add link to ITIF report

### PR DESCRIPTION
**Pull request by annahsebok**
Updating vote.gov description to include link to ITIF report.

### CODE REVIEW

**Comment by annahsebok** [comment]
@amirbey based on the formatting of the other link on this page, I included the space before the link as opposed to after it. If I add a space after the link, wouldn't there then be two spaces? I wasn't sure.

**Comment by wslack** [comment]
You need on both sides, just like a word has a space on each side of it!

**Comment by annahsebok** [comment]
@wslack (cc @amirbey) of course it does! Clearly my brain was tired when I typed my last comment. Just merged that space change to this branch, so this should be good to go now!

**Comment by annahsebok** [comment]
@wslack forgive my github newbiness — do I need to wait for @amirbey to dismiss his review now that I've made the correction, or is that something I can do in order to then merge?

**Comment by wslack** [comment]
I don't know if you can dismiss it but feel free to if the issue is simple and 100% resolved. I took care of it this time!

**Pull request merged**
