### PR TITLE
Development Container (Docker)

### PR DESCRIPTION
**Pull request by dhcole**
Packaging Federalist as a Docker container makes it for new team members and others interested in the project to quickly get started running the application locally. 

Since Federalist ties together several frameworks and applications (node.js, Sails.js, ruby, Jekyll, localtunnel / ngrok) it can be challenging to get a local environment set up, and it's often unnecessary to do so when simply reviewing the application.

The PR makes a few changes to Federalist to make it ready for running in a container:

- Override GitHub oauth if a "personal access token" is provided
- Set up a `localtunnel` and set the webhook callback to it (when running in development)
- Run `jekyll` with `bundle exec` to ensure dependencies are in scope

And this PR sets up a Dockerfile for building Federalist into a docker image. That image is [published on the Docker Hub](https://hub.docker.com/r/18fgsa/federalist/)

### Deploy Federalist from the Docker Hub:

1. Download and install the [Docker Toolbox](https://www.docker.com/toolbox)
2. Set up a GitHub [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/)
3. Open Kitematic on your Mac (it's installed with the Docker Toolkit), search for "Federalist", and click create:
  screen shot 2015-08-25 at 4 54 22 pm
4. Click "Settings", paste your personal access token next to `GITHUB_TOKEN`, and click "Save"
  screen shot 2015-08-25 at 4 55 00 pm
5. Click "Home" and you'll see the log of Federalist starting up. (You may need to wait a minute for the application to start up.) Click the arrow next to "Web Preview" to open up Federalist in your browser:
  screen shot 2015-08-25 at 4 55 18 pm
6. You're now running Federalist in a local container and you can do all the things you'd usually do with it
  screen shot 2015-08-25 at 4 55 57 pm
  screen shot 2015-08-25 at 4 56 06 pm
  screen shot 2015-08-25 at 4 56 09 pm
7. **Bonus:** you can try our other branches of Federalist (useful for reviewing pull requests). Get the branch  name from GitHub:
  screen shot 2015-08-25 at 4 56 49 pm
8. Go back to "Settings" in Kitematic, set the `BRANCH` environment variable, and click "Save":
  screen shot 2015-08-25 at 4 56 57 pm
9. Now on "Home", you'll see the log of the application checking out the branch and rebuilding. Give it a minute, then open the web preview:
screen shot 2015-08-25 at 4 57 34 pm
10. You now have the application running with the new branch.
  screen shot 2015-08-25 at 4 57 46 pm
  screen shot 2015-08-25 at 4 58 09 pm
  screen shot 2015-08-25 at 5 00 26 pm

### CODE REVIEW

**Comment by jeremiak** [comment]
This is so cool! Very easy to install and get running :smile: 

I'm having an issue getting the most current `master` branch to display properly. I updated the `branch` setting to be master, waited for Docker to pull it down and build it, and then when I go to look at the preview it looks like the `npm install` tasks didn't get run because there is no style sheet:



Any ideas @dhcole?

**Comment by dhcole** [comment]
@jeremiak did it work when you first loaded the container (with no branch)? I think this is because there is no dockerfile or `docker-start.sh` script in the remote master. It should be a temporary problem resolved by merging.

**Comment by jeremiak** [comment]
Cool, sounds like a good theory. Merging now

**Comment by afeld** [comment]
Awesome thorough instructions! Moved them to a [wiki page](https://github.com/18F/federalist/wiki/Deploy-Federalist-from-the-Docker-Hub) for more visibility – hope that's ok!

**Pull request merged**
