### PR TITLE
Updating dashboard header

### PR DESCRIPTION
**Pull request by line47**
Moved the image inside of the heading tag to make consistent with the pages header.

**In addition**
Removed the redundant `Websites` header and made `Dashboard` an `H2` which follows the format of the sub pages.

I think we could even go one step further and remove the `Dashboard` heading as I feel that `Your websites` is enough to convey what is being shown on the page and the word Dashboard isn't necessary. 

# Before screenshot
screen shot 2018-01-02 at 2 55 07 pm

# After screenshot
screen shot 2018-01-02 at 2 53 07 pm

CC @wslack

### CODE REVIEW

**Comment by wslack** [comment]
I think we should remove "your websites" or replace "dashboard" with "your websites"

**Comment by wslack** [comment]
100% agree that both aren't needed; good point

**Comment by line47** [comment]
@wslack - I'm thinking of going with `Your websites` like the screesnshot below. 
Let me know if that's good.

screen shot 2018-01-02 at 4 07 03 pm

**Comment by wslack** [comment]
@line47 I would suggest moving the text down - that way all pages have the same title below the icon, which seems more consistant.

This screenshot puts the page title where the "repo name" typically goes.

**Comment by line47** [comment]
What text would go next to the icon ? 

I think it looks strange to have an icon then a new line for the page name, thoughts?

screen shot 2018-01-02 at 4 47 03 pm

**Comment by wslack** [comment]
This is my thought after fiddling for a sec:
screen shot 2018-01-02 at 4 52 45 pm

**Comment by wslack** [comment]
Which, on second thought, can go next to the icon. I would want the text and the icon to have the same height, though.

**Comment by jseppi** [comment]
Is this still a WIP or ready for final review?

**Comment by line47** [comment]
This is ready for review 👍

**Pull request merged**
