### PR TITLE
Release - 2021-02-17

### PR DESCRIPTION
**Pull request by svenaas**
## Changes proposed in this pull request:
- Parameterize app name #3709
- Refresh DNS table (and de/provision button) after admin domain de/provision #3727
- Replace admin organization delete button with de/activate buttons (Pages) #3728
- Upgrade node, remove DNS workaround #3737
- Allow selection of demo context when creating domains through admin UI #3758
- Correctly set site engine when adding a site #3761
- Update .codeclimate.yml #3762
- Remove nsp from federalist codeclimate pipeline #3764
- Fix .audit() calls in controllers #3771
- Only configure UAA if feature flag is set #3774 
- Add script to create a Federalist environment #3776
- Add GitHub auth for queues UI, completely separate bull board from the rest of the application, update config #3780

## Post deployment
- Record these changes in the next sprint architecture review following their deployment.

## security considerations
- CodeClimate change adds more static code analysis
- Environment creation script presents gitleaks findings but these have been manually verified and represent no real leaks. An issue has been created for preventing false positives when using environment variable.
- Allowing Github authentication for queues UI based on membership in `federalist-admins` GH org, same as admin interface.

### CODE REVIEW

**Comment by svenaas** [comment]
@18F/federalist-admins I've made this a draft and have left the data incomplete until we decide when we want to merge this. Do you think I'm missing anything in deployment or security considerations above?

**Comment by svenaas** [comment]
Provisionally making this a tomorrow thing. @18F/federalist-admins, please do adjust "Post Deployment" and "Security Considerations" on this as you think best!

**Comment by svenaas** [comment]
(Because it's for sure not gonna be a Friday thing!)

**Comment by svenaas** [comment]
Renamed this to reflect next *Tuesday* and knocked it back down to draft. 

Since I wrote the description two more PRs have been merged into staging (#3765 and #3766) and there are currently five more PRs pending against staging, at least three of which are ready for review. We'll need to revisit this next week and decide what goes in and what stays out.

**Comment by svenaas** [comment]
@davemcorwin @apburnes I've believe I've pulled in **security considerations** from all the staging PRs which are wrapped up in this one. Can you think of anything that belongs in the **post deployment** section up top?

**Comment by apburnes** [comment]
The doc hasn't been updated for this sprint yet, but we've been adding Federalist updates to the sprint architecture review so it's a good place to add the release highlights.

**Comment by svenaas** [comment]
When I updated the spring architecture review last time I directly lifted the list of changes from our latest `main` releases.

**Comment by svenaas** [comment]
But I'll note that up top! It's a good reminder.

**Comment by svenaas** [comment]
So CircleCI is timing out on `federalist-queues-ui-staging` and of course Concourse can't do Pages staging stuff so there are a lot of red Xes. FWIW the rest of Circle's checks are OK:

- [build](https://circleci.com/gh/18F/federalist/100563?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
- [deploy-admin-staging](https://circleci.com/gh/18F/federalist/100565?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
- [deploy-staging](https://circleci.com/gh/18F/federalist/100566?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
- [run-migrations-staging](https://circleci.com/gh/18F/federalist/100568?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
- [deploy-queues-ui-staging](https://circleci.com/gh/18F/federalist/100567?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed

**Comment by svenaas** [comment]
OK, @18F/federalist-admins, CircleCI has now passed this one through `build-test-deploy` — thanks, I believe, to @davemcorwin's queues ui work — and we'd all benefit from your review.

**Review by davemcorwin — APPROVED** [review]
LG

**Pull request merged**
