### PR TITLE
Added brightness overlay on .figure images & removed whitespace

### PR DESCRIPTION
**Pull request by ctrimm**
This addresses issue #1810 in a very simple PR.

The issue is that when scrolling thru the main landing page, the images do not particularly stand out against the white background of the page. So, a simple solution suggested by @ericronne was to add a darker background and then change the transparency of all the images. I took a slightly different approach by adding `filter: brightness(95%)` to the `img` tags inside of `.figure` div's.

Here are some screenshots of what my proposed solution looks like - 
screen shot 2018-06-29 at 3 10 22 pm
screen shot 2018-06-29 at 3 10 19 pm
screen shot 2018-06-29 at 3 10 15 pm

You can see that there isn't really a background on the Agency Logos screenshot - this is because they all happen to be circular `.png` images. Whereas the screenshots of sample sites are rectangular.

If you would like to have the agency logos with a similar gray background, we can simply apply `background-color: $color-gray-lightest;` to the `img` tag styling.

### CODE REVIEW

**Comment by ctrimm** [comment]
This was manually tested in Chrome 67. However, I realized when I ran IE10 on Windows 7 inside of VirtualBox that IE10 and below does not support filter/brightness. This can also be [verified here](https://caniuse.com/#search=CSS%20filter) that it will only work in IE11 and above.

I can dig into this deeper if you all would like. If not, feel free to ask questions/give feedback/etc.

**Comment by wslack** [comment]
Thank you @ctrimm! I am headed out for the day but we will look at this early next week!

**Comment by ericronne** [comment]
Neat! Thanks, @ctrimm!

The agency logos should all be designed to run over white already, so our solution should exclude them.

**Comment by ctrimm** [comment]
@ericronne The `filter` property only affects colored pixels - so, it'll still add the brightness filter to the agency logos - but the change in negligible, in my opinion. You can verify this by inspecting the DOM.

**Pull request merged**
