### PR TITLE
Add cache-control header

### PR DESCRIPTION
**Pull request by jmhooper**
Since the app is served in front of CloudFront, the API needs a Cache-Control header to tell CloudFront not to cache API response. This commit adds a middleware in `app.js` to make that happen.

### CODE REVIEW

**Comment by jmhooper** [comment]
@jseppi: 👍 will update

**Comment by jseppi** [comment]
It would also be great if there was a test that covered this :)

**Comment by jmhooper** [comment]
@jseppi: I've added tests to check for the Cache-Control header

**Comment by wslack** [comment]
@jseppi is the test 👍 ?

**Pull request merged**
