### PR TITLE
[WIP] Navigation updates for new IA

### PR DESCRIPTION
**Pull request by jseppi**
**work-in-progress**

ref #1027

To Do:
- [x] test - Original coverage is only at 60% so we should bring that up as part of this PR.

### CODE REVIEW

**Comment by jseppi** [comment]
Use gear icon for new Users link in nav

**Comment by jseppi** [comment]
We didn't really have icons for "GitHub branches" or "Data on S3" so I used some currently unused sprites we had. They're not the best representations, especially the one for "GitHub branches."

screen shot 2017-10-05 at 9 43 15 am

**Comment by wslack** [comment]
That's fine for now.

**Comment by jseppi** [comment]
superseded by #1216

**Pull request closed without merging**
