### PR TITLE
Excise remaining sails cruft

### PR DESCRIPTION
**Pull request by jseppi**
This PR removes all remaining mentions of "sails" from the repository. Mostly these deletions were lines in dotfiles.

Also:
* Cleared out `.codeclimate.yml`, which was excluding paths to things that didn't even exist. This led me to take a quick look at the project on Code Climate, where I noticed that it doesn't look to be configured properly, so I filed #941.
* ~Deleted `exportSitesAsCsv.js` and associated bash script and npm task. This file looks like it was never converted after the initial removal of sails, so I am guessing it isn't used anywhere and is thus just vestigial code. Please confirm, @jmhooper. This is related to #938 as well.~
* Added new `scripts/lint-diff.sh` and `lint:diff` task in `package.json` to locally lint changed files. `scripts/lint-travis.sh` has now been modified to use `lint-diff.sh` internally.

To Do:
- [x] figure out why `npm run test:prepare` is failing on Travis. It is not failing locally.
- [x] un-`sails`-ify `exportSitesAsCsv.js`

Ref #935

### CODE REVIEW

**Comment by jmhooper** [comment]
The `exportSitesAsCsv.js` is actually used, though apparently it hasn't been used recently 😳 . It's used by the `download-sites-export` script: https://github.com/18F/federalist/blob/staging/scripts/download-sites-export.sh

Moreover, being able to download the list of sites to see what is on Federalist will probably be a requisite for the coming ATO.

**Comment by jmhooper** [comment]
Looks good. Have we actually done this on the backend in api.data.gov?

**Comment by jseppi** [comment]
Not quite sure what you mean about api.data.gov

**Comment by jmhooper** [comment]
I... am in the wrong issue. Was reviewing a totally different project and apparently changed to the wrong tab 😳

**Comment by jseppi** [comment]
@jmhooper I have no idea why the Travis build is failing. It says `bundle.js` is missing during `npm test:prepare` (ref https://travis-ci.org/18F/federalist/builds/236138872#L1718). Any ideas?

**Comment by jmhooper** [comment]
@jseppi: It looks like the deletion of `public/js/dependencies/sails.io.js` took `public/js` with it. We'll need to add `public/js/.keep` to the repo to get it back.

**Comment by jseppi** [comment]
oh geez, thanks for figuring that out!

**Comment by jseppi** [comment]
Ready for review, @jmhooper!

**Comment by jseppi** [comment]
@jmhooper donezo!

**Pull request merged**
